version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  perf_consumer:
    profiles: ["test"]
    image: pivotalrabbitmq/perf-test:latest
    depends_on:
      - consumer
    command: [
      "-h",
      "amqp://guest:guest@rabbitmq:5672/%2f",
      "-z",
      "40",
      "-ct",
      "1",
      "--rate",
      "70000",
      "--json-body",
      "--size",
      "256",
      "--producers",
      "1",
      "--consumers",
      "0",
      "--exchange",
      "bench.direct",
      "--queue",
      "consume-test",
      "--predeclared",
      "--routing-key",
      "testing",
      "--use-millis"
    ]

  perf_producer:
    profiles: ["test"]
    image: pivotalrabbitmq/perf-test:latest
    depends_on:
      - consumer
    command: [
      "-h",
      "amqp://guest:guest@rabbitmq:5672/%2f",
      "-z",
      "2000",
      "-ct",
      "1",
      "--producers",
      "0",
      "--consumers",
      "1",
      "--qos",
      "100",
      "--multi-ack-every",
      "100",
      "--exchange",
      "bench.direct",
      "--queue",
      "consume-test",
      "--predeclared",
      "--routing-key",
      "testing",
      "--use-millis"
    ]

  consumer:
    image: makeomatic/node:16-tester
    depends_on:
      - rabbitmq
    volumes:
      - ../../:/src
    working_dir: /src/packages/benchmarks
    command: /bin/sh -c "pnpm -r run compile && exec tail -f /dev/null"
    environment:
      - NODE_ENV=production
